version: '3'

services:
  backend:
    image: kayvan999/email-generation-backend:latest
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: email-generation-backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    image: kayvan999/email-generation-frontend:latest
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: email-generation-frontend
    ports:
      - 3000:3000
    env_file:
      - .env
    command: sh -c "npm start"