version: '3'

services:
  backend:
    image: kayvan999/email-generation-backend:latest
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    env_file:
      - .env
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"

  frontend:
    image: kayvan999/email-generation-frontend:latest
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    env_file:
      - .env
    command: sh -c "npm start"