name: Docker Image

on:
  pull_request:
    branches: [ "main" ]
    types:
        - closed
  workflow_dispatch:
  
jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
        
    steps:  
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/email-generation-frontend:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-and-push-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
        
    steps:  
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/email-generation-backend:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

    
